name: Merge Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pull request info
        id: pr-info
        run: |
          echo "::set-output name=approvals::$(curl -s -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews | jq '.[] | select(.state == \"APPROVED\")' | jq length)"

      - name: Merge pull request if approved
        if: ${{ steps.pr-info.outputs.approvals == 2 }} # Change the number of required approvals as needed
        run: |
          # Merge pull request using GitHub API
          # Example command: curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge
