name: PR Merge Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge-if-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required approvals
        id: check-approvals
        run: |
          approvals=$(jq -r '.pull_request.reviews[] | select(.state == "approved") | .user.login' $GITHUB_EVENT_PATH | sort -u | wc -l)
          echo "::set-output name=approvals::$approvals"

      - name: Merge PR if approved
        if: ${{ steps.check-approvals.outputs.approvals == '2' }}
        run: |
          echo "Two approvals received. Merging PR now."
          # Добавьте здесь команду для слияния пулл реквеста
